### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by treagod** [electricduck/vscode-elementary-theme#2]
Hi!

really awesome project, love it that I can now use the elementary color palette.  But I think the purple sidebar doesn't match the overall design. Maybe use the iconic blue elementary theme color? Or make it more neutral and use a darker tone of the explorer color?

Anyways, I'm using this theme from now on! Thanks man

**Comment by electricduck** [comment]
![image](https://user-images.githubusercontent.com/1594644/98284418-ffadc380-1f98-11eb-8791-80d11008ea88.png)

The basis behind the purple color (Grape, as its known with elementary's palette) is its usually used for developer-orientated stuff, as seen on the above screenshot. The sidebar was actually originally a darker shade of the explorer color, but the Grape color gives it some emphasis for the rest of the UI, along with giving it the "developer" flair from the palette. Admittedly, however, Code (elementaryOS's Code) doesn't use this color at all.

I suppose it could be worth also having variants that let you either have a colorful or dark version of the sidebar.

**Comment by treagod** [comment]
I think having more color variants is a good idea. Then the user has more options to personalize his workspace :)

**Comment by rbribeiro** [comment]
As an attempt of preserving the use of Grape as a suggestion of the developer nature of VS Code, I made the following modification in your theme:
[https://rodrigoribeirosite.files.wordpress.com/2020/11/screenshot-from-2020-11-08-15.06.45.png](https://rodrigoribeirosite.files.wordpress.com/2020/11/screenshot-from-2020-11-08-15.06.45.png)

Another possibility that looks beautiful as well is changing the background of an active button to grape.

**Comment by treagod** [comment]
I really like this change. I think the way you preserve that grape color in a subtle way is the way to go

**Comment by electricduck** [comment]
There are now **Lighter** and **Darker** variants in **1.51.2** that include the inverted sidebars.

@treagod Is this more or less what you had in mind?

**Comment by treagod** [comment]
Yes, that's perfect! Thank you so much .
